server:
  port: 8080
spring:
  interface-clients:
    http:
      client-groups:
        verificationClient:
          base-url: http://localhost:8081
  application:
    name: http-verification-client


logging:
  level:
    org.springframework.boot: debug